name:                photosys
version:             0.1.0.0
github:              "githubuser/photosys"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/photosys#readme>

dependencies:
- name: base 
  version: ">= 4.7 && < 5"
  mixin:
    - hiding (Prelude)
- name: relude
  mixin:
    - (Relude as Prelude, Relude.Unsafe)
- lens
- generic-lens
- threepenny-gui
- comonad
- aeson
- filepath

default-extensions:
- LambdaCase
- RecordWildCards
- OverloadedStrings
- DerivingStrategies
- DeriveGeneric
- DeriveFunctor

library:
  source-dirs: src

executables:
  photosys-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - photosys

tests:
  photosys-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - photosys
